version: '3'
services:
  db:
    image: "postgres:9.6"
#    volumes:
#      - "dbdata:/var/lib/postgresql/data"
    env_file:
      - .env
#    networks:
#      - db_nw
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
#    networks:
#      - db_nw
    depends_on:
      - db
#networks:
#  db_nw:
#    driver: bridge
#volumes:
#  dbdata: